### ISSUE TITLE
Found error in arguments

### ISSUE THREAD

**Issue by cyxou** [jonschlinkert/write-banner#1]
Hi! thanks for this module.
I try to make your module work as cli tool and found a bug in it. When I call 

```
writeBanner('foo.txt', 'output.txt', {banner: 'banner.tmpl'});
```

I get this error:

E:\Documents\GitHub\write-banner\node_modules\strip-banner\node_modules\strip-comments\index.js:35
  return str ? str.replace(re, '') : '';
                   ^
TypeError: Object #<Object> has no method 'replace' at strip.banner (E:\Documents\GitHub\write-banner\node_modules\strip-banner\node_modules\strip-comments\index.js:35:20)
    at module.exports (E:\Documents\GitHub\write-banner\node_modules\add-banner\index.js:71:19)
    at writeBanner (E:\Documents\GitHub\write-banner\index.js:26:20)
    at Object.<anonymous> (E:\Documents\GitHub\write-banner\bin\write-banner-cli.js:16:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

Getting into the code reveals the problem in the [index.js file](https://github.com/jonschlinkert/write-banner/blob/master/index.js#L26). The banner function should be called with two args, where the first one is the src variable:

```
write.sync(dest, banner(src, opts) + str);
```

**Comment by jonschlinkert** [comment]
thanks for creating the issue. would you like to do a pr? or I can fix, let me know, thanks!

**Comment by cyxou** [comment]
Hi, I'll make a pr asap

**Comment by cyxou** [comment]
Created the pr to address this issue
